version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_DATASERVICE=localhost:3002
      - PORT=3000
  ds:
    build: ../PhotoBook-DS
    restart: always
    ports:
      - "3002:3002"
    environment:
      - DB_CON_STR=mongodb://mongouser:il0vemongoDB!@cpsc559-mongodbatlas-cluster-shard-00-00-r1lqr.azure.mongodb.net:27017,cpsc559-mongodbatlas-cluster-shard-00-01-r1lqr.azure.mongodb.net:27017,cpsc559-mongodbatlas-cluster-shard-00-02-r1lqr.azure.mongodb.net:27017/photobook?ssl=true&replicaSet=CPSC559-mongodbAtlas-cluster-shard-0&authSource=admin&retryWrites=true
      - USE_SSL=true